---

env:
  node: true
  es2020: true

plugins:
  - jest

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  no-await-in-loop: 0
  no-restricted-syntax:
    - 'error'
#    - 'ForInStatement'
#    - 'ForOfStatement'
    - 'LabeledStatement'
    - 'WithStatement'
  # разрешает подчёркивание в именах только для двух констант
  no-underscore-dangle:
    - 2
    - allow: [__filename, __dirname]
